#
# colors.h
#
# list of ansi color codes
# provided by xiutils
#

export RESET=$(printf "[0m")
export BOLD=$(printf "[0;1m")
export BLACK=$(printf "[0;30m")
export RED=$(printf "[0;31m")
export GREEN=$(printf "[0;32m")
export YELLOW=$(printf "[0;33m")
export BLUE=$(printf "[0;34m")
export MAGENTA=$(printf "[0;35m")
export CYAN=$(printf "[0;36m")
export WHITE=$(printf "[0;37m")
export DEFAULT=$(printf "[0;39m")
export BG_BLACK=$(printf "[40m")
export BG_RED=$(printf "[41m")
export BG_GREEN=$(printf "[42m")
export BG_YELLOW=$(printf "[43m")
export BG_BLUE=$(printf "[44m")
export BG_MAGENTA=$(printf "[45m")
export BG_CYAN=$(printf "[46m")
export BG_WHITE=$(printf "[47m")
export BG_DEFAULT=$(printf "[49m")
export LIGHT_BLACK=$(printf "[0;90m")
export LIGHT_RED=$(printf "[0;91m")
export LIGHT_GREEN=$(printf "[0;92m")
export LIGHT_YELLOW=$(printf "[0;93m")
export LIGHT_BLUE=$(printf "[0;94m")
export LIGHT_MAGENTA=$(printf "[0;95m")
export LIGHT_CYAN=$(printf "[0;96m")
export LIGHT_WHITE=$(printf "[0;97m")
export LIGHT_DEFAULT=$(printf "[0;99m")
export BOLDBLACK=$(printf "[1;30m")
export BOLDRED=$(printf "[1;31m")
export BOLDGREEN=$(printf "[1;32m")
export BOLDYELLOW=$(printf "[1;33m")
export BOLDBLUE=$(printf "[1;34m")
export BOLDMAGENTA=$(printf "[1;35m")
export BOLDCYAN=$(printf "[1;36m")
export BOLDWHITE=$(printf "[1;37m")
