/*
 * colors.h
 *
 * list of ansi color codes
 * provided by xiutils
 *
 */

#define RESET "[0m"
#define BOLD "[0;1m"
#define BLACK "[0;30m"
#define RED "[0;31m"
#define GREEN "[0;32m"
#define YELLOW "[0;33m"
#define BLUE "[0;34m"
#define MAGENTA "[0;35m"
#define CYAN "[0;36m"
#define WHITE "[0;37m"
#define DEFAULT "[0;39m"
#define BG_BLACK "[40m"
#define BG_RED "[41m"
#define BG_GREEN "[42m"
#define BG_YELLOW "[43m"
#define BG_BLUE "[44m"
#define BG_MAGENTA "[45m"
#define BG_CYAN "[46m"
#define BG_WHITE "[47m"
#define BG_DEFAULT "[49m"
#define LIGHT_BLACK "[0;90m"
#define LIGHT_RED "[0;91m"
#define LIGHT_GREEN "[0;92m"
#define LIGHT_YELLOW "[0;93m"
#define LIGHT_BLUE "[0;94m"
#define LIGHT_MAGENTA "[0;95m"
#define LIGHT_CYAN "[0;96m"
#define LIGHT_WHITE "[0;97m"
#define LIGHT_DEFAULT "[0;99m"
#define BOLDBLACK "[1;30m"
#define BOLDRED "[1;31m"
#define BOLDGREEN "[1;32m"
#define BOLDYELLOW "[1;33m"
#define BOLDBLUE "[1;34m"
#define BOLDMAGENTA "[1;35m"
#define BOLDCYAN "[1;36m"
#define BOLDWHITE "[1;37m"
